
// Objective-C API for talking to the following Go packages
//
//	github.com/mysteriumnetwork/node/mobile/mysterium
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mysterium_FRAMEWORK_H__
#define __Mysterium_FRAMEWORK_H__

#include "Mysterium.objc.h"
#include "Universe.objc.h"

#endif
