// Objective-C API for talking to github.com/mysteriumnetwork/node/mobile/mysterium Go package.
//   gobind -lang=objc github.com/mysteriumnetwork/node/mobile/mysterium
//
// File is generated by gobind. Do not edit.

#ifndef __Mysterium_H__
#define __Mysterium_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MysteriumBuildInfo;
@class MysteriumConnectRequest;
@class MysteriumConnectResponse;
@class MysteriumConsumerPaymentConfig;
@class MysteriumCreateOrderRequest;
@class MysteriumGetBalanceRequest;
@class MysteriumGetBalanceResponse;
@class MysteriumGetIdentityRegistrationFeesResponse;
@class MysteriumGetIdentityRequest;
@class MysteriumGetIdentityResponse;
@class MysteriumGetLocationResponse;
@class MysteriumGetOrderRequest;
@class MysteriumGetProposalRequest;
@class MysteriumGetProposalsRequest;
@class MysteriumGetStatusResponse;
@class MysteriumHealthCheckData;
@class MysteriumListOrdersRequest;
@class MysteriumMobileNode;
@class MysteriumMobileNodeOptions;
@class MysteriumOrderResponse;
@class MysteriumOrderUpdatedCallbackPayload;
@class MysteriumRegisterIdentityRequest;
@class MysteriumSendFeedbackRequest;
@protocol MysteriumBalanceChangeCallback;
@class MysteriumBalanceChangeCallback;
@protocol MysteriumConnectionStatusChangeCallback;
@class MysteriumConnectionStatusChangeCallback;
@protocol MysteriumIdentityRegistrationChangeCallback;
@class MysteriumIdentityRegistrationChangeCallback;
@protocol MysteriumOrderUpdatedCallback;
@class MysteriumOrderUpdatedCallback;
@protocol MysteriumProposalChangeCallback;
@class MysteriumProposalChangeCallback;
@protocol MysteriumStatisticsChangeCallback;
@class MysteriumStatisticsChangeCallback;
@protocol MysteriumWireguardTunnelSetup;
@class MysteriumWireguardTunnelSetup;

@protocol MysteriumBalanceChangeCallback <NSObject>
- (void)onChange:(NSString* _Nullable)identityAddress balance:(double)balance;
@end

@protocol MysteriumConnectionStatusChangeCallback <NSObject>
- (void)onChange:(NSString* _Nullable)status;
@end

@protocol MysteriumIdentityRegistrationChangeCallback <NSObject>
- (void)onChange:(NSString* _Nullable)identityAddress status:(NSString* _Nullable)status;
@end

@protocol MysteriumOrderUpdatedCallback <NSObject>
- (void)onUpdate:(MysteriumOrderUpdatedCallbackPayload* _Nullable)payload;
@end

@protocol MysteriumProposalChangeCallback <NSObject>
- (void)onChange:(NSData* _Nullable)proposal;
@end

@protocol MysteriumStatisticsChangeCallback <NSObject>
- (void)onChange:(int64_t)duration bytesReceived:(int64_t)bytesReceived bytesSent:(int64_t)bytesSent tokensSpent:(double)tokensSpent;
@end

@protocol MysteriumWireguardTunnelSetup <NSObject>
- (void)addDNS:(NSString* _Nullable)ip;
- (void)addRoute:(NSString* _Nullable)route prefixLen:(long)prefixLen;
- (void)addTunnelAddress:(NSString* _Nullable)ip prefixLen:(long)prefixLen;
- (BOOL)establish:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)newTunnel;
- (BOOL)protect:(long)socket error:(NSError* _Nullable* _Nullable)error;
- (void)setBlocking:(BOOL)blocking;
- (void)setMTU:(long)mtu;
- (void)setSessionName:(NSString* _Nullable)session;
@end

/**
 * BuildInfo represents node build info.
 */
@interface MysteriumBuildInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull commit;
@property (nonatomic) NSString* _Nonnull branch;
@property (nonatomic) NSString* _Nonnull buildNumber;
@end

/**
 * ConnectRequest represents connect request.
 */
@interface MysteriumConnectRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identityAddress;
@property (nonatomic) NSString* _Nonnull providerID;
@property (nonatomic) NSString* _Nonnull serviceType;
@property (nonatomic) BOOL disableKillSwitch;
@property (nonatomic) BOOL forceReconnect;
@end

/**
 * ConnectResponse represents connect response with optional error code and message.
 */
@interface MysteriumConnectResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull errorCode;
@property (nonatomic) NSString* _Nonnull errorMessage;
@end

/**
 * ConsumerPaymentConfig defines consumer side payment configuration
 */
@interface MysteriumConsumerPaymentConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull pricePerGIBMax;
@property (nonatomic) NSString* _Nonnull pricePerGIBMin;
@property (nonatomic) NSString* _Nonnull pricePerMinuteMax;
@property (nonatomic) NSString* _Nonnull pricePerMinuteMin;
@end

/**
 * CreateOrderRequest a request to create an order.
 */
@interface MysteriumCreateOrderRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identityAddress;
@property (nonatomic) double mystAmount;
@property (nonatomic) NSString* _Nonnull payCurrency;
@property (nonatomic) BOOL lightning;
@end

/**
 * GetBalanceRequest represents balance request.
 */
@interface MysteriumGetBalanceRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identityAddress;
@end

/**
 * GetBalanceResponse represents balance response.
 */
@interface MysteriumGetBalanceResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) double balance;
@end

/**
 * GetIdentityRegistrationFeesResponse represents identity registration fees result.
 */
@interface MysteriumGetIdentityRegistrationFeesResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) double fee;
@end

/**
 * GetIdentityRequest represents identity request.
 */
@interface MysteriumGetIdentityRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull passphrase;
@end

/**
 * GetIdentityResponse represents identity response.
 */
@interface MysteriumGetIdentityResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identityAddress;
@property (nonatomic) NSString* _Nonnull channelAddress;
@property (nonatomic) NSString* _Nonnull registrationStatus;
@end

/**
 * GetLocationResponse represents location response.
 */
@interface MysteriumGetLocationResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull ip;
@property (nonatomic) NSString* _Nonnull country;
@end

/**
 * GetOrderRequest a request to get an order.
 */
@interface MysteriumGetOrderRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identityAddress;
@property (nonatomic) int64_t id_;
@end

/**
 * GetProposalRequest represents proposal request.
 */
@interface MysteriumGetProposalRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull providerID;
@property (nonatomic) NSString* _Nonnull serviceType;
@end

/**
 * GetProposalsRequest represents proposals request.
 */
@interface MysteriumGetProposalsRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull serviceType;
@property (nonatomic) BOOL refresh;
@property (nonatomic) BOOL includeFailed;
@property (nonatomic) double upperTimePriceBound;
@property (nonatomic) double lowerTimePriceBound;
@property (nonatomic) double upperGBPriceBound;
@property (nonatomic) double lowerGBPriceBound;
@end

/**
 * GetStatusResponse represents status response.
 */
@interface MysteriumGetStatusResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull state;
@property (nonatomic) NSString* _Nonnull providerID;
@property (nonatomic) NSString* _Nonnull serviceType;
@end

/**
 * HealthCheckData represents node health check info.
 */
@interface MysteriumHealthCheckData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull uptime;
@property (nonatomic) NSString* _Nonnull version;
@property (nonatomic) MysteriumBuildInfo* _Nullable buildInfo;
@end

/**
 * ListOrdersRequest a request to list orders.
 */
@interface MysteriumListOrdersRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identityAddress;
@end

/**
 * MobileNode represents node object tuned for mobile device.
 */
@interface MysteriumMobileNode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Connect connects to given provider.
 */
- (MysteriumConnectResponse* _Nullable)connect:(MysteriumConnectRequest* _Nullable)req;
/**
 * CreateOrder creates a payment order.
 */
- (NSData* _Nullable)createOrder:(MysteriumCreateOrderRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * Currencies lists supported payment currencies.
 */
- (NSData* _Nullable)currencies:(NSError* _Nullable* _Nullable)error;
/**
 * Disconnect disconnects or cancels current connection.
 */
- (BOOL)disconnect:(NSError* _Nullable* _Nullable)error;
/**
 * GetBalance returns current balance.
 */
- (MysteriumGetBalanceResponse* _Nullable)getBalance:(MysteriumGetBalanceRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * GetConsumerPaymentConfig returns consumer payment config
 */
- (MysteriumConsumerPaymentConfig* _Nullable)getConsumerPaymentConfig;
/**
 * GetDefaultCurrency returns the current default currency set.
 */
- (NSString* _Nonnull)getDefaultCurrency;
/**
 * GetIdentity finds first identity and unlocks it.
If there is no identity default one will be created.
 */
- (MysteriumGetIdentityResponse* _Nullable)getIdentity:(MysteriumGetIdentityRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * GetIdentityRegistrationFees returns identity registration fees.
 */
- (MysteriumGetIdentityRegistrationFeesResponse* _Nullable)getIdentityRegistrationFees:(NSError* _Nullable* _Nullable)error;
/**
 * GetLocation return current location including country and IP.
 */
- (MysteriumGetLocationResponse* _Nullable)getLocation:(NSError* _Nullable* _Nullable)error;
/**
 * GetOrder gets an order by ID.
 */
- (NSData* _Nullable)getOrder:(MysteriumGetOrderRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * GetProposals returns service proposals from API or cache. Proposals returned as JSON byte array since
go mobile does not support complex slices.
 */
- (NSData* _Nullable)getProposals:(MysteriumGetProposalsRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * GetStatus returns current connection state and provider info if connected to VPN.
 */
- (MysteriumGetStatusResponse* _Nullable)getStatus;
/**
 * HealthCheck returns node health check data.
 */
- (MysteriumHealthCheckData* _Nullable)healthCheck;
/**
 * ListOrders lists all payment orders.
 */
- (NSData* _Nullable)listOrders:(MysteriumListOrdersRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * OverrideWireguardConnection overrides default wireguard connection implementation to more mobile adapted one.
 */
- (void)overrideWireguardConnection:(id<MysteriumWireguardTunnelSetup> _Nullable)wgTunnelSetup;
/**
 * Reconnect checks weather session is alive and reconnects if its dead. Force reconnect if ForceReconnect is set.
 */
- (MysteriumConnectResponse* _Nullable)reconnect:(MysteriumConnectRequest* _Nullable)req;
/**
 * RegisterBalanceChangeCallback registers callback which is called on identity balance change.
 */
- (void)registerBalanceChangeCallback:(id<MysteriumBalanceChangeCallback> _Nullable)cb;
/**
 * RegisterConnectionStatusChangeCallback registers callback which is called on active connection
status change.
 */
- (void)registerConnectionStatusChangeCallback:(id<MysteriumConnectionStatusChangeCallback> _Nullable)cb;
/**
 * RegisterIdentity starts identity registration in background.
 */
- (BOOL)registerIdentity:(MysteriumRegisterIdentityRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * RegisterIdentityRegistrationChangeCallback registers callback which is called on identity registration status change.
 */
- (void)registerIdentityRegistrationChangeCallback:(id<MysteriumIdentityRegistrationChangeCallback> _Nullable)cb;
/**
 * RegisterOrderUpdatedCallback registers OrderStatusChanged callback.
 */
- (void)registerOrderUpdatedCallback:(id<MysteriumOrderUpdatedCallback> _Nullable)cb;
/**
 * RegisterStatisticsChangeCallback registers callback which is called on active connection
statistics change.
 */
- (void)registerStatisticsChangeCallback:(id<MysteriumStatisticsChangeCallback> _Nullable)cb;
/**
 * SendFeedback sends user feedback via feedback reported.
 */
- (BOOL)sendFeedback:(MysteriumSendFeedbackRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
/**
 * Shutdown function stops running mobile node.
 */
- (BOOL)shutdown:(NSError* _Nullable* _Nullable)error;
/**
 * WaitUntilDies function returns when node stops.
 */
- (BOOL)waitUntilDies:(NSError* _Nullable* _Nullable)error;
@end

/**
 * MobileNodeOptions contains common mobile node options.
 */
@interface MysteriumMobileNodeOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL testnet2;
@property (nonatomic) BOOL localnet;
@property (nonatomic) BOOL experimentNATPunching;
@property (nonatomic) NSString* _Nonnull mysteriumAPIAddress;
// skipped field MobileNodeOptions.BrokerAddresses with unsupported type: []string

@property (nonatomic) NSString* _Nonnull etherClientRPC;
@property (nonatomic) NSString* _Nonnull feedbackURL;
@property (nonatomic) NSString* _Nonnull qualityOracleURL;
@property (nonatomic) NSString* _Nonnull ipDetectorURL;
@property (nonatomic) NSString* _Nonnull locationDetectorURL;
@property (nonatomic) NSString* _Nonnull transactorEndpointAddress;
@property (nonatomic) NSString* _Nonnull hermesEndpointAddress;
@property (nonatomic) int64_t chainID;
@property (nonatomic) NSString* _Nonnull pilvytisAddress;
@property (nonatomic) NSString* _Nonnull mystSCAddress;
@property (nonatomic) NSString* _Nonnull registrySCAddress;
@property (nonatomic) NSString* _Nonnull hermesSCAddress;
@property (nonatomic) NSString* _Nonnull channelImplementationSCAddress;
@end

/**
 * OrderResponse represents a payment order for mobile usage.
 */
@interface MysteriumOrderResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t id_;
@property (nonatomic) NSString* _Nonnull identityAddress;
@property (nonatomic) NSString* _Nonnull status;
@property (nonatomic) double mystAmount;
// skipped field OrderResponse.PayCurrency with unsupported type: *string

// skipped field OrderResponse.PayAmount with unsupported type: *float64

@property (nonatomic) NSString* _Nonnull paymentAddress;
@property (nonatomic) NSString* _Nonnull paymentURL;
@end

/**
 * OrderUpdatedCallbackPayload is the payload of OrderUpdatedCallback.
 */
@interface MysteriumOrderUpdatedCallbackPayload : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t orderID;
@property (nonatomic) NSString* _Nonnull status;
@property (nonatomic) double payAmount;
@property (nonatomic) NSString* _Nonnull payCurrency;
@end

/**
 * RegisterIdentityRequest represents identity registration request.
 */
@interface MysteriumRegisterIdentityRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identityAddress;
@property (nonatomic) NSString* _Nonnull token;
@end

/**
 * SendFeedbackRequest represents user feedback request.
 */
@interface MysteriumSendFeedbackRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull email;
@property (nonatomic) NSString* _Nonnull description;
@end

/**
 * DefaultNodeOptions returns default options.
 */
FOUNDATION_EXPORT MysteriumMobileNodeOptions* _Nullable MysteriumDefaultNodeOptions(void);

/**
 * NewNode function creates new Node.
 */
FOUNDATION_EXPORT MysteriumMobileNode* _Nullable MysteriumNewNode(NSString* _Nullable appPath, MysteriumMobileNodeOptions* _Nullable options, NSError* _Nullable* _Nullable error);

@class MysteriumBalanceChangeCallback;

@class MysteriumConnectionStatusChangeCallback;

@class MysteriumIdentityRegistrationChangeCallback;

@class MysteriumOrderUpdatedCallback;

@class MysteriumProposalChangeCallback;

@class MysteriumStatisticsChangeCallback;

@class MysteriumWireguardTunnelSetup;

/**
 * BalanceChangeCallback represents balance change callback.
 */
@interface MysteriumBalanceChangeCallback : NSObject <goSeqRefInterface, MysteriumBalanceChangeCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onChange:(NSString* _Nullable)identityAddress balance:(double)balance;
@end

/**
 * ConnectionStatusChangeCallback represents status callback.
 */
@interface MysteriumConnectionStatusChangeCallback : NSObject <goSeqRefInterface, MysteriumConnectionStatusChangeCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onChange:(NSString* _Nullable)status;
@end

/**
 * IdentityRegistrationChangeCallback represents identity registration status callback.
 */
@interface MysteriumIdentityRegistrationChangeCallback : NSObject <goSeqRefInterface, MysteriumIdentityRegistrationChangeCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onChange:(NSString* _Nullable)identityAddress status:(NSString* _Nullable)status;
@end

/**
 * OrderUpdatedCallback is a callback when order status changes.
 */
@interface MysteriumOrderUpdatedCallback : NSObject <goSeqRefInterface, MysteriumOrderUpdatedCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onUpdate:(MysteriumOrderUpdatedCallbackPayload* _Nullable)payload;
@end

/**
 * ProposalChangeCallback represents proposal callback.
 */
@interface MysteriumProposalChangeCallback : NSObject <goSeqRefInterface, MysteriumProposalChangeCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onChange:(NSData* _Nullable)proposal;
@end

/**
 * StatisticsChangeCallback represents statistics callback.
 */
@interface MysteriumStatisticsChangeCallback : NSObject <goSeqRefInterface, MysteriumStatisticsChangeCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onChange:(int64_t)duration bytesReceived:(int64_t)bytesReceived bytesSent:(int64_t)bytesSent tokensSpent:(double)tokensSpent;
@end

/**
 * WireguardTunnelSetup exposes api for caller to implement external tunnel setup
 */
@interface MysteriumWireguardTunnelSetup : NSObject <goSeqRefInterface, MysteriumWireguardTunnelSetup> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)addDNS:(NSString* _Nullable)ip;
- (void)addRoute:(NSString* _Nullable)route prefixLen:(long)prefixLen;
- (void)addTunnelAddress:(NSString* _Nullable)ip prefixLen:(long)prefixLen;
- (BOOL)establish:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)newTunnel;
- (BOOL)protect:(long)socket error:(NSError* _Nullable* _Nullable)error;
- (void)setBlocking:(BOOL)blocking;
- (void)setMTU:(long)mtu;
- (void)setSessionName:(NSString* _Nullable)session;
@end

#endif
